/**
 * Copyright (c) 2015-present, Facebook, Inc. All rights reserved.
 *
 * <p>You are hereby granted a non-exclusive, worldwide, royalty-free license to use, copy, modify,
 * and distribute this software in source code or binary form for use in connection with the web
 * services and APIs provided by Facebook.
 *
 * <p>As with any software that integrates with the Facebook platform, your use of this software is
 * subject to the Facebook Developer Principles and Policies [http://developers.facebook.com/policy/].
 * This copyright notice shall be included in all copies or substantial portions of the software.
 *
 * <p>THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
 * BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package com.facebook.ads.sdk.serverside;

import com.google.gson.annotations.SerializedName;
import java.util.Objects;

public class AttributionData {
    @SerializedName("scope")
    private String scope = null;

    @SerializedName("visit_time")
    private Long visitTime = null;

    @SerializedName("ad_id")
    private String adId = null;

    @SerializedName("adset_id")
    private String adsetId = null;

    @SerializedName("campaign_id")
    private String campaignId = null;

    @SerializedName("attribution_share")
    private Float attributionShare = null;

    @SerializedName("attribution_model")
    private AttributionModelEnum attributionModel = null;

    @SerializedName("attr_window")
    private Integer attributionWindow = null;

    @SerializedName("attribution_value")
    private Float attributionValue = null;

    @SerializedName("attribution_source")
    private String attributionSource = null;

    @SerializedName("touchpoint_type")
    private String touchpointType = null;

    @SerializedName("touchpoint_ts")
    private Integer touchpointTs = null;

    @SerializedName("attribution_method")
    private AttributionMethodEnum attributionMethod = null;

    @SerializedName("decline_reason")
    private DeclineReasonEnum declineReason = null;

    @SerializedName("auditing_token")
    private String auditingToken = null;

    @SerializedName("linkage_key")
    private String linkageKey = null;

    @SerializedName("attribution_setting")
    private AttributionSetting attributionSetting = null;
    
    /**
     * Default constructor
     */
    public AttributionData() {
    }

    /**
     * Constructor
     * 
     * @param scope Touchpoint type
     * @param visitTime Time that the campaign_id or fbc was first received
     * @param adId Meta-provided ad id from URL/deeplink
     * @param adsetId Meta-provided adset id from URL/deeplink
     * @param campaignId Meta-provided campaign id from URL/deeplink
     * @param attributionShare [0-1] weight of credit assigned to the visit
     * @param attributionModel Attribution model used to attribute the event
     * @param attributionWindow Attribution window in days
     * @param attributionValue The share of value generated by this click-conversion pair that is attributed to Meta.
     * @param attributionSource The attribution source to differentiate the source of the data, e.g. whether this is from AMM or Custom Attribution or any other sources.
     * @param touchpointType The engagement type that caused the original credited conversion.
     * @param touchpointTs The time when the touchpoint event occurred with the ad that the install was credited to.
     * @param attributionMethod The attribution method used to attribute the event.
     * @param declineReason The decline reason for the attribution.
     * @param auditingToken The auditing token for the attribution.
     * @param linkageKey The linkage key for the attribution.
     * @param attributionSetting The attribution setting with inactivity and reattribution window configuration.
     */
    public AttributionData(String scope, Long visitTime, String adId, String adsetId, String campaignId, 
        Float attributionShare, AttributionModelEnum attributionModel, Integer attributionWindow, Float attributionValue,
        String attributionSource, String touchpointType, Integer touchpointTs, AttributionMethodEnum attributionMethod,
        DeclineReasonEnum declineReason, String auditingToken, String linkageKey, AttributionSetting attributionSetting) {
      this.scope = scope;
      this.visitTime = visitTime;
      this.adId = adId;
      this.adsetId = adsetId;
      this.campaignId = campaignId;
      this.attributionShare = attributionShare;
      this.attributionModel = attributionModel;
      this.attributionWindow = attributionWindow;
      this.attributionValue = attributionValue;
      this.attributionSource = attributionSource;
      this.touchpointType = touchpointType;
      this.touchpointTs = touchpointTs;
      this.attributionMethod = attributionMethod;
      this.declineReason = declineReason;
      this.auditingToken = auditingToken;
      this.linkageKey = linkageKey;
      this.attributionSetting = attributionSetting;
    }

    /**
     * Set scope
     * 
     * @param scope Touchpoint type
     * @return AttributionData
     */
    public AttributionData scope(String scope) {
      this.scope = scope;
      return this;
    }

    /**
     * Get scope
     * 
     * @return scope
     */
    public String getScope() {
      return scope;
    }

    /**
     * Set scope
     * 
     * @param scope Touchpoint type
     */
    public void setScope(String scope) {
      this.scope = scope;
    }

    /**
     * Set visitTime
     * 
     * @param visitTime Time that the campaign_id or fbc was first received
     * @return AttributionData
     */
    public AttributionData visitTime(Long visitTime) {
      this.visitTime = visitTime;
      return this;
    }

    /**
     * Get visitTime
     * 
     * @return visitTime
     */
    public Long getVisitTime() {
      return visitTime;
    }

    /**
     * Set visitTime
     * 
     * @param visitTime Time that the campaign_id or fbc was first received
     */
    public void setVisitTime(Long visitTime) {
      this.visitTime = visitTime;
    }

    /**
     * Set adId
     * 
     * @param adId Meta-provided ad id from URL/deeplink
     * @return AttributionData
     */
    public AttributionData adId(String adId) {
      this.adId = adId;
      return this;
    }

    /**
     * Get adId
     * 
     * @return adId
     */
    public String getAdId() {
      return adId;
    }

    /**
     * Set adId
     * 
     * @param adId Meta-provided ad id from URL/deeplink
     */
    public void setAdId(String adId) {
      this.adId = adId;
    }

    /**
     * Set adsetId
     * 
     * @param adsetId Meta-provided adset id from URL/deeplink
     * @return AttributionData
     */
    public AttributionData adsetId(String adsetId) {
      this.adsetId = adsetId;
      return this;
    }

    /**
     * Get adsetId
     * 
     * @return adsetId
     */
    public String getAdsetId() {
      return adsetId;
    }

    /**
     * Set adsetId
     * 
     * @param adsetId Meta-provided adset id from URL/deeplink
     */
    public void setAdsetId(String adsetId) {
      this.adsetId = adsetId;
    }

    /**
     * Set campaignId
     * 
     * @param campaignId Meta-provided campaign id from URL/deeplink
     * @return AttributionData
     */
    public AttributionData campaignId(String campaignId) {
      this.campaignId = campaignId;
      return this;
    }

    /**
     * Get campaignId
     * 
     * @return campaignId
     */
    public String getCampaignId() {
      return campaignId;
    }

    /**
     * Set campaignId
     * 
     * @param campaignId Meta-provided campaign id from URL/deeplink
     */
    public void setCampaignId(String campaignId) {
      this.campaignId = campaignId;
    }

    /**
     * Set attributionShare
     * 
     * @param attributionShare [0-1] weight of credit assigned to the visit
     * @return AttributionData
     */
    public AttributionData attributionShare(Float attributionShare) {
      this.attributionShare = attributionShare;
      return this;
    }

    /**
     * Get attributionShare
     * 
     * @return attributionShare
     */
    public Float getAttributionShare() {
      return attributionShare;
    }

    /**
     * Set attributionShare
     * 
     * @param attributionShare [0-1] weight of credit assigned to the visit
     */
    public void setAttributionShare(Float attributionShare) {
      this.attributionShare = attributionShare;
    }

    /**
     * Set attributionModel
     * 
     * @param attributionModel Attribution model used to attribute the event.
     * @return AttributionData
     */
    public AttributionData attributionModel(AttributionModelEnum attributionModel) {
      this.attributionModel = attributionModel;
      return this;
    }

    /**
     * Get attributionModel
     * 
     * @return attributionModel
     */
    public AttributionModelEnum getAttributionModel() {
      return attributionModel;
    }

    /**
     * Set attributionModel
     * 
     * @param attributionModel Attribution model used to attribute the event.
     */
    public void setAttributionModel(AttributionModelEnum attributionModel) {
      this.attributionModel = attributionModel;
    }

    /**
     * Set attributionWindow
     * 
     * @param attributionWindow Attribution window in days.
     * @return AttributionData
     */
    public AttributionData attributionWindow(Integer attributionWindow) {
        this.attributionWindow = attributionWindow;
        return this;
      }
  
      /**
       * Get attributionWindow
       * 
       * @return attributionWindow
       */
      public Integer getAttributionWindow() {
        return attributionWindow;
      }
  
      /**
       * Set attributionWindow
       * 
       * @param attributionWindow Attribution window in days.
       */
      public void setAttributionWindow(Integer attributionWindow) {
        this.attributionWindow = attributionWindow;
      }

    /**
     * Set attributionValue
     *
     * @param attributionValue The share of value generated by this click-conversion pair that is attributed to Meta.
     * @return AttributionData
     */
    public AttributionData attributionValue(Float attributionValue) {
        this.attributionValue = attributionValue;
        return this;
    }

    /**
     * Get attributionValue
     *
     * @return attributionValue
     */
    public Float getAttributionValue() {
        return attributionValue;
    }

    /**
     * Set attributionValue
     *
     * @param attributionValue The share of value generated by this click-conversion pair that is attributed to Meta.
     */
    public void setAttributionValue(Float attributionValue) {
        this.attributionValue = attributionValue;
    }

    /**
     * Set attributionSource
     * 
     * @param attributionSource The attribution source to differentiate the source of the data, e.g. whether this is from AMM or Custom Attribution or any other sources.
     * @return AttributionData
     */
    public AttributionData attributionSource(String attributionSource) {
      this.attributionSource = attributionSource;
      return this;
    }

    /**
     * Get attributionSource
     * 
     * @return attributionSource
     */
    public String getAttributionSource() {
      return attributionSource;
    }

    /**
     * Set attributionSource
     * 
     * @param attributionSource The attribution source to differentiate the source of the data, e.g. whether this is from AMM or Custom Attribution or any other sources.
     */
    public void setAttributionSource(String attributionSource) {
      this.attributionSource = attributionSource;
    }

    /**
     * Set touchpointType
     * 
     * @param touchpointType The engagement type that caused the original credited conversion.
     * @return AttributionData
     */
    public AttributionData touchpointType(String touchpointType) {
      this.touchpointType = touchpointType;
      return this;
    }

    /**
     * Get touchpointType
     * 
     * @return touchpointType
     */
    public String getTouchpointType() {
      return touchpointType;
    }

    /**
     * Set touchpointType
     * 
     * @param touchpointType The engagement type that caused the original credited conversion.
     */
    public void setTouchpointType(String touchpointType) {
      this.touchpointType = touchpointType;
    }

    /**
     * Set touchpointTs
     * 
     * @param touchpointTs The time when the touchpoint event occurred with the ad that the install was credited to.
     * @return AttributionData
     */
    public AttributionData touchpointTs(Integer touchpointTs) {
      this.touchpointTs = touchpointTs;
      return this;
    }

    /**
     * Get touchpointTs
     * 
     * @return touchpointTs
     */
    public Integer getTouchpointTs() {
      return touchpointTs;
    }

    /**
     * Set touchpointTs
     * 
     * @param touchpointTs The time when the touchpoint event occurred with the ad that the install was credited to.
     */
    public void setTouchpointTs(Integer touchpointTs) {
      this.touchpointTs = touchpointTs;
    }

    /**
     * Set attributionMethod
     * 
     * @param attributionMethod The attribution method used to attribute the event.
     * @return AttributionData
     */
    public AttributionData attributionMethod(AttributionMethodEnum attributionMethod) {
      this.attributionMethod = attributionMethod;
      return this;
    }

    /**
     * Get attributionMethod
     * 
     * @return attributionMethod
     */
    public AttributionMethodEnum getAttributionMethod() {
      return attributionMethod;
    }

    /**
     * Set attributionMethod
     * 
     * @param attributionMethod The attribution method used to attribute the event.
     */
    public void setAttributionMethod(AttributionMethodEnum attributionMethod) {
      this.attributionMethod = attributionMethod;
    }

    /**
     * Set declineReason
     * 
     * @param declineReason The decline reason for the attribution.
     * @return AttributionData
     */
    public AttributionData declineReason(DeclineReasonEnum declineReason) {
      this.declineReason = declineReason;
      return this;
    }

    /**
     * Get declineReason
     * 
     * @return declineReason
     */
    public DeclineReasonEnum getDeclineReason() {
      return declineReason;
    }

    /**
     * Set declineReason
     * 
     * @param declineReason The decline reason for the attribution.
     */
    public void setDeclineReason(DeclineReasonEnum declineReason) {
      this.declineReason = declineReason;
    }

    /**
     * Set auditingToken
     * 
     * @param auditingToken The auditing token for the attribution.
     * @return AttributionData
     */
    public AttributionData auditingToken(String auditingToken) {
      this.auditingToken = auditingToken;
      return this;
    }

    /**
     * Get auditingToken
     * 
     * @return auditingToken
     */
    public String getAuditingToken() {
      return auditingToken;
    }

    /**
     * Set auditingToken
     * 
     * @param auditingToken The auditing token for the attribution.
     */
    public void setAuditingToken(String auditingToken) {
      this.auditingToken = auditingToken;
    }

    /**
     * Set linkageKey
     * 
     * @param linkageKey The linkage key for the attribution.
     * @return AttributionData
     */
    public AttributionData linkageKey(String linkageKey) {
      this.linkageKey = linkageKey;
      return this;
    }

    /**
     * Get linkageKey
     * 
     * @return linkageKey
     */
    public String getLinkageKey() {
      return linkageKey;
    }

    /**
     * Set linkageKey
     * 
     * @param linkageKey The linkage key for the attribution.
     */
    public void setLinkageKey(String linkageKey) {
      this.linkageKey = linkageKey;
    }

    /**
     * Set attributionSetting
     * 
     * @param attributionSetting The attribution setting with inactivity and reattribution window configuration.
     * @return AttributionData
     */
    public AttributionData attributionSetting(AttributionSetting attributionSetting) {
      this.attributionSetting = attributionSetting;
      return this;
    }

    /**
     * Get attributionSetting
     * 
     * @return attributionSetting
     */
    public AttributionSetting getAttributionSetting() {
      return attributionSetting;
    }

    /**
     * Set attributionSetting
     * 
     * @param attributionSetting The attribution setting with inactivity and reattribution window configuration.
     */
    public void setAttributionSetting(AttributionSetting attributionSetting) {
      this.attributionSetting = attributionSetting;
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;

      AttributionData attributionData = (AttributionData) o;

      return Objects.equals(this.scope, attributionData.scope)
        && Objects.equals(this.visitTime, attributionData.visitTime)
        && Objects.equals(this.adId, attributionData.adId)
        && Objects.equals(this.adsetId, attributionData.adsetId)
        && Objects.equals(this.campaignId, attributionData.campaignId)
        && Objects.equals(this.attributionShare, attributionData.attributionShare)
        && Objects.equals(this.attributionModel, attributionData.attributionModel)
        && Objects.equals(this.attributionWindow, attributionData.attributionWindow)
        && Objects.equals(this.attributionValue, attributionData.attributionValue)
        && Objects.equals(this.attributionSource, attributionData.attributionSource)
        && Objects.equals(this.touchpointType, attributionData.touchpointType)
        && Objects.equals(this.touchpointTs, attributionData.touchpointTs)
        && Objects.equals(this.attributionMethod, attributionData.attributionMethod)
        && Objects.equals(this.declineReason, attributionData.declineReason)
        && Objects.equals(this.auditingToken, attributionData.auditingToken)
        && Objects.equals(this.linkageKey, attributionData.linkageKey)
        && Objects.equals(this.attributionSetting, attributionData.attributionSetting);
    }

    @Override
    public int hashCode() {
      return Objects.hash(scope, visitTime, adId, adsetId, campaignId, attributionShare, attributionModel, attributionWindow, attributionValue, attributionSource, touchpointType, touchpointTs, attributionMethod, declineReason, auditingToken, linkageKey, attributionSetting);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder();
      sb.append("class AttributionData {\n");
      sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
      sb.append("    visitTime: ").append(toIndentedString(visitTime)).append("\n");
      sb.append("    adId: ").append(toIndentedString(adId)).append("\n");
      sb.append("    adsetId: ").append(toIndentedString(adsetId)).append("\n");
      sb.append("    campaignId: ").append(toIndentedString(campaignId)).append("\n");
      sb.append("    attributionShare: ").append(toIndentedString(attributionShare)).append("\n");
      sb.append("    attributionModel: ").append(toIndentedString(attributionModel)).append("\n");
      sb.append("    attributionWindow: ").append(toIndentedString(attributionWindow)).append("\n");
      sb.append("    attributionValue: ").append(toIndentedString(attributionValue)).append("\n");
      sb.append("    attributionSource: ").append(toIndentedString(attributionSource)).append("\n");
      sb.append("    touchpointType: ").append(toIndentedString(touchpointType)).append("\n");
      sb.append("    touchpointTs: ").append(toIndentedString(touchpointTs)).append("\n");
      sb.append("    attributionMethod: ").append(toIndentedString(attributionMethod)).append("\n");
      sb.append("    declineReason: ").append(toIndentedString(declineReason)).append("\n");
      sb.append("    auditingToken: ").append(toIndentedString(auditingToken)).append("\n");
      sb.append("    linkageKey: ").append(toIndentedString(linkageKey)).append("\n");
      sb.append("    attributionSetting: ").append(toIndentedString(attributionSetting)).append("\n");
      sb.append("}");
      return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
      if (o == null) {
        return "null";
      }
      return o.toString().replace("\n", "\n    ");
    }
}
