package com.facebook.ads.sdk.insights;

import com.google.gson.annotations.SerializedName;

/**
 * Author: Xardas
 * Date: 26.03.16
 * Time: 21:25
 */
public enum InsightsFieldsEnum {
  @SerializedName("frequency_value")
  VALUE_FREQUENCY_VALUE("frequency_value"),
  @SerializedName("age")
  VALUE_AGE("age"),
  @SerializedName("country")
  VALUE_COUNTRY("country"),
  @SerializedName("gender")
  VALUE_GENDER("gender"),
  @SerializedName("impression_device")
  VALUE_IMPRESSION_DEVICE("impression_device"),
  @SerializedName("place_page_id")
  VALUE_PLACE_PAGE_ID("place_page_id"),
  @SerializedName("placement")
  VALUE_PLACEMENT("placement"),
  @SerializedName("product_id")
  VALUE_PRODUCT_ID("product_id"),
  @SerializedName("region")
  VALUE_REGION("region"),
  @SerializedName("hourly_stats_aggregated_by_advertiser_time_zone")
  VALUE_HOURLY_STATS_AGGREGATED_BY_ADVERTISER_TIME_ZONE("hourly_stats_aggregated_by_advertiser_time_zone"),
  @SerializedName("hourly_stats_aggregated_by_audience_time_zone")
  VALUE_HOURLY_STATS_AGGREGATED_BY_AUDIENCE_TIME_ZONE("hourly_stats_aggregated_by_audience_time_zone"),
  @SerializedName("account_id")
  VALUE_ACCOUNT_ID("account_id"),
  @SerializedName("account_name")
  VALUE_ACCOUNT_NAME("account_name"),
  @SerializedName("action_values")
  VALUE_ACTION_VALUES("action_values"),
  @SerializedName("actions")
  VALUE_ACTIONS("actions"),
  @SerializedName("unique_actions")
  VALUE_UNIQUE_ACTIONS("unique_actions"),
  @SerializedName("app_store_clicks")
  VALUE_APP_STORE_CLICKS("app_store_clicks"),
  @SerializedName("buying_type")
  VALUE_BUYING_TYPE("buying_type"),
  @SerializedName("call_to_action_clicks")
  VALUE_CALL_TO_ACTION_CLICKS("call_to_action_clicks"),
  @SerializedName("card_views")
  VALUE_CARD_VIEWS("card_views"),
  @SerializedName("unique_clicks")
  VALUE_UNIQUE_CLICKS("unique_clicks"),
  @SerializedName("cost_per_action_type")
  VALUE_COST_PER_ACTION_TYPE("cost_per_action_type"),
  @SerializedName("cost_per_unique_action_type")
  VALUE_COST_PER_UNIQUE_ACTION_TYPE("cost_per_unique_action_type"),
  @SerializedName("cost_per_inline_post_engagement")
  VALUE_COST_PER_INLINE_POST_ENGAGEMENT("cost_per_inline_post_engagement"),
  @SerializedName("cost_per_inline_link_click")
  VALUE_COST_PER_INLINE_LINK_CLICK("cost_per_inline_link_click"),
  @SerializedName("cost_per_total_action")
  VALUE_COST_PER_TOTAL_ACTION("cost_per_total_action"),
  @SerializedName("cost_per_10_sec_video_view")
  VALUE_COST_PER_10_SEC_VIDEO_VIEW("cost_per_10_sec_video_view"),
  @SerializedName("cost_per_unique_click")
  VALUE_COST_PER_UNIQUE_CLICK("cost_per_unique_click"),
  @SerializedName("cpm")
  VALUE_CPM("cpm"),
  @SerializedName("cpp")
  VALUE_CPP("cpp"),
  @SerializedName("ctr")
  VALUE_CTR("ctr"),
  @SerializedName("unique_ctr")
  VALUE_UNIQUE_CTR("unique_ctr"),
  @SerializedName("unique_link_clicks_ctr")
  VALUE_UNIQUE_LINK_CLICKS_CTR("unique_link_clicks_ctr"),
  @SerializedName("date_start")
  VALUE_DATE_START("date_start"),
  @SerializedName("date_stop")
  VALUE_DATE_STOP("date_stop"),
  @SerializedName("deeplink_clicks")
  VALUE_DEEPLINK_CLICKS("deeplink_clicks"),
  @SerializedName("frequency")
  VALUE_FREQUENCY("frequency"),
  @SerializedName("impressions")
  VALUE_IMPRESSIONS("impressions"),
  @SerializedName("unique_impressions")
  VALUE_UNIQUE_IMPRESSIONS("unique_impressions"),
  @SerializedName("inline_link_clicks")
  VALUE_INLINE_LINK_CLICKS("inline_link_clicks"),
  @SerializedName("inline_post_engagement")
  VALUE_INLINE_POST_ENGAGEMENT("inline_post_engagement"),
  @SerializedName("newsfeed_avg_position")
  VALUE_NEWSFEED_AVG_POSITION("newsfeed_avg_position"),
  @SerializedName("newsfeed_clicks")
  VALUE_NEWSFEED_CLICKS("newsfeed_clicks"),
  @SerializedName("newsfeed_impressions")
  VALUE_NEWSFEED_IMPRESSIONS("newsfeed_impressions"),
  @SerializedName("reach")
  VALUE_REACH("reach"),
  @SerializedName("relevance_score")
  VALUE_RELEVANCE_SCORE("relevance_score"),
  @SerializedName("social_clicks")
  VALUE_SOCIAL_CLICKS("social_clicks"),
  @SerializedName("unique_social_clicks")
  VALUE_UNIQUE_SOCIAL_CLICKS("unique_social_clicks"),
  @SerializedName("social_impressions")
  VALUE_SOCIAL_IMPRESSIONS("social_impressions"),
  @SerializedName("unique_social_impressions")
  VALUE_UNIQUE_SOCIAL_IMPRESSIONS("unique_social_impressions"),
  @SerializedName("social_reach")
  VALUE_SOCIAL_REACH("social_reach"),
  @SerializedName("social_spend")
  VALUE_SOCIAL_SPEND("social_spend"),
  @SerializedName("spend")
  VALUE_SPEND("spend"),
  @SerializedName("total_action_value")
  VALUE_TOTAL_ACTION_VALUE("total_action_value"),
  @SerializedName("total_actions")
  VALUE_TOTAL_ACTIONS("total_actions"),
  @SerializedName("total_unique_actions")
  VALUE_TOTAL_UNIQUE_ACTIONS("total_unique_actions"),
  @SerializedName("video_avg_pct_watched_actions")
  VALUE_VIDEO_AVG_PCT_WATCHED_ACTIONS("video_avg_pct_watched_actions"),
  @SerializedName("video_avg_sec_watched_actions")
  VALUE_VIDEO_AVG_SEC_WATCHED_ACTIONS("video_avg_sec_watched_actions"),
  @SerializedName("video_complete_watched_actions")
  VALUE_VIDEO_COMPLETE_WATCHED_ACTIONS("video_complete_watched_actions"),
  @SerializedName("video_p25_watched_actions")
  VALUE_VIDEO_P25_WATCHED_ACTIONS("video_p25_watched_actions"),
  @SerializedName("video_p50_watched_actions")
  VALUE_VIDEO_P50_WATCHED_ACTIONS("video_p50_watched_actions"),
  @SerializedName("video_p75_watched_actions")
  VALUE_VIDEO_P75_WATCHED_ACTIONS("video_p75_watched_actions"),
  @SerializedName("video_p95_watched_actions")
  VALUE_VIDEO_P95_WATCHED_ACTIONS("video_p95_watched_actions"),
  @SerializedName("video_p100_watched_actions")
  VALUE_VIDEO_P100_WATCHED_ACTIONS("video_p100_watched_actions"),
  @SerializedName("video_10_sec_watched_actions")
  VALUE_VIDEO_10_SEC_WATCHED_ACTIONS("video_10_sec_watched_actions"),
  @SerializedName("video_15_sec_watched_actions")
  VALUE_VIDEO_15_SEC_WATCHED_ACTIONS("video_15_sec_watched_actions"),
  @SerializedName("video_30_sec_watched_actions")
  VALUE_VIDEO_30_SEC_WATCHED_ACTIONS("video_30_sec_watched_actions"),
  @SerializedName("website_clicks")
  VALUE_WEBSITE_CLICKS("website_clicks"),
  @SerializedName("website_ctr")
  VALUE_WEBSITE_CTR("website_ctr"),
  @SerializedName("ad_id")
  VALUE_AD_ID("ad_id"),
  @SerializedName("ad_name")
  VALUE_AD_NAME("ad_name"),
  @SerializedName("adset_id")
  VALUE_ADSET_ID("adset_id"),
  @SerializedName("adset_name")
  VALUE_ADSET_NAME("adset_name"),
  @SerializedName("campaign_id")
  VALUE_CAMPAIGN_ID("campaign_id"),
  @SerializedName("campaign_name")
  VALUE_CAMPAIGN_NAME("campaign_name"),
  @SerializedName("objective")
  VALUE_OBJECTIVE("objective"),
  @SerializedName("action_carousel_card_id")
  VALUE_ACTION_CAROUSEL_CARD_ID("action_carousel_card_id"),
  @SerializedName("action_carousel_card_name")
  VALUE_ACTION_CAROUSEL_CARD_NAME("action_carousel_card_name"),
  @SerializedName("clicks")
  VALUE_CLICKS("clicks"),
  @SerializedName("unique_inline_link_clicks")
  VALUE_UNIQUE_INLINE_LINK_CLICKS("unique_inline_link_clicks"),
  @SerializedName("cost_per_unique_inline_link_click")
  VALUE_COST_PER_UNIQUE_INLINE_LINK_CLICK("cost_per_unique_inline_link_click"),
  @SerializedName("inline_link_click_ctr")
  VALUE_INLINE_LINK_CLICK_CTR("inline_link_click_ctr"),
  @SerializedName("unique_inline_link_click_ctr")
  VALUE_UNIQUE_INLINE_LINK_CLICK_CTR("unique_inline_link_click_ctr"),
  @SerializedName("cpc")
  VALUE_CPC("cpc"),
  @SerializedName("estimated_ad_recallers")
  VALUE_ESTIMATED_AD_RECALLERS("estimated_ad_recallers"),
  @SerializedName("estimated_ad_recallers_lower_bound")
  VALUE_ESTIMATED_AD_RECALLERS_LOWER_BOUND("estimated_ad_recallers_lower_bound"),
  @SerializedName("estimated_ad_recallers_upper_bound")
  VALUE_ESTIMATED_AD_RECALLERS_UPPER_BOUND("estimated_ad_recallers_upper_bound"),
  @SerializedName("estimated_ad_recall_rate")
  VALUE_ESTIMATED_AD_RECALL_RATE("estimated_ad_recall_rate"),
  @SerializedName("estimated_ad_recall_rate_lower_bound")
  VALUE_ESTIMATED_AD_RECALL_RATE_LOWER_BOUND("estimated_ad_recall_rate_lower_bound"),
  @SerializedName("estimated_ad_recall_rate_upper_bound")
  VALUE_ESTIMATED_AD_RECALL_RATE_UPPER_BOUND("estimated_ad_recall_rate_upper_bound"),
  @SerializedName("cost_per_estimated_ad_recallers")
  VALUE_COST_PER_ESTIMATED_AD_RECALLERS("cost_per_estimated_ad_recallers"),
  @SerializedName("canvas_avg_view_time")
  VALUE_CANVAS_AVG_VIEW_TIME("canvas_avg_view_time"),
  @SerializedName("canvas_avg_view_percent")
  VALUE_CANVAS_AVG_VIEW_PERCENT("canvas_avg_view_percent"),
  @SerializedName("place_page_name")
  VALUE_PLACE_PAGE_NAME("place_page_name"),
  @SerializedName("ad_bid_type")
  VALUE_AD_BID_TYPE("ad_bid_type"),
  @SerializedName("ad_bid_value")
  VALUE_AD_BID_VALUE("ad_bid_value"),
  @SerializedName("ad_delivery")
  VALUE_AD_DELIVERY("ad_delivery"),
  @SerializedName("adset_bid_type")
  VALUE_ADSET_BID_TYPE("adset_bid_type"),
  @SerializedName("adset_bid_value")
  VALUE_ADSET_BID_VALUE("adset_bid_value"),
  @SerializedName("adset_budget_type")
  VALUE_ADSET_BUDGET_TYPE("adset_budget_type"),
  @SerializedName("adset_budget_value")
  VALUE_ADSET_BUDGET_VALUE("adset_budget_value"),
  @SerializedName("adset_delivery")
  VALUE_ADSET_DELIVERY("adset_delivery"),
  @SerializedName("adset_start")
  VALUE_ADSET_START("adset_start"),
  @SerializedName("adset_end")
  VALUE_ADSET_END("adset_end"),
  NULL(null);

  private String value;

  private InsightsFieldsEnum(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return value;
  }
}