name: Publish package to the Maven Central Repository
on: [push, pull_request]
  #release:
  #  types: [created]
  #pull_request:
  #  types: [opened, edited]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        run: |
          openssl aes-256-cbc -K $encrypted_1285e1ddfb82_key -iv $encrypted_1285e1ddfb82_iv -in keyring.gpg.enc -out keyring.gpg -d
          gpg --import keyring.gpg
      - name: Publish package
        run: mvn -B deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
